import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router-dom";

import DraftTabB from "../DraftTabB";
import { LanguageProvider } from "../../../../i18n/context/LanguageContext";
import { draftStore } from "../../../storage";
import { createEmptyBrief } from "../../../../types/storyBrief";
import type { Story } from "../../../../types/story";
import type { Agent1Result } from "../../../../types/agent1Result";

// Regression coverage for the "approve the wrong version" bug: the Draft tab
// tracked which version was on screen only in local `selectedVersionIndex`
// state, but Approve used to fire a bare status transition with no reference
// to that selection — so the server approved whatever `currentDraft` happened
// to already be persisted, not what the specialist was actually looking at.

jest.mock("../../../storage", () => ({
  draftStore: {
    transitionStatus: jest.fn(),
    updateStory: jest.fn(),
    generateVariant: jest.fn(),
    runAgent1Regeneration: jest.fn(),
    createStory: jest.fn(),
    updateBrief: jest.fn(),
  },
}));

const mockTransitionStatus = draftStore.transitionStatus as jest.MockedFunction<
  typeof draftStore.transitionStatus
>;

function makeVersion(overrides: Partial<Agent1Result>): Agent1Result {
  return {
    generationId: "gen-1",
    emotionalTruth: "Fear can shrink with support.",
    blueprint: [
      { index: 1, text: "Setup" },
      { index: 2, text: "Worry appears" },
      { index: 3, text: "Support arrives" },
      { index: 4, text: "Practice tool" },
      { index: 5, text: "Small success" },
      { index: 6, text: "Calm ending" },
    ],
    copingToolPlacement: "middle",
    approachInstruction: "Use calm validating language.",
    title: "Story title",
    story: "Story body text used for the word count check in this test.",
    wordCount: 11,
    targetWordRange: [1, 100],
    wordCountDrift: "within_range",
    alignmentNote: "Aligned.",
    postValidationFlags: [],
    preCheckWarnings: [],
    exampleBankStatus: "examples_used",
    rerunCount: 0,
    totalLatencyMs: 100,
    llmCalls: [],
    generatedAt: new Date().toISOString(),
    ...overrides,
  };
}

function makeStory(overrides: Partial<Story> = {}): Story {
  const v1 = makeVersion({ generationId: "gen-1", title: "V1 title", story: "V1 body sentence for approve test." });
  const v2 = makeVersion({
    generationId: "gen-2",
    title: "V2 title (GPT variant)",
    story: "V2 body sentence, generated by the GPT variant.",
    modelChoice: "gpt",
  });
  const now = Date.now();
  return {
    id: "story-1",
    ownerUid: "specialist-1",
    parentStoryId: null,
    title: "V2 title (GPT variant)",
    storyType: "fear_anxiety",
    ageRange: "5-7",
    tags: [],
    status: "in_review",
    briefStatus: "submitted",
    brief: createEmptyBrief(),
    agent1Result: v2,
    agent1Versions: [v1, v2],
    currentDraft: { title: v2.title, body: v2.story, wordCount: v2.wordCount, updatedAt: now },
    pages: [{ pageNumber: 1, text: v2.story, wordCount: v2.wordCount }],
    editHistory: [],
    illustrationPages: null,
    currentVisualBibleVersion: null,
    illustrationWorkspaceOpenedAt: null,
    publishedAt: null,
    publishedTemplateId: null,
    createdAt: now,
    updatedAt: now,
    lastOpenedAt: now,
    submittedAt: now,
    approvedAt: null,
    ...overrides,
  };
}

function renderDraftTab(story: Story) {
  return render(
    <MemoryRouter initialEntries={["/he/specialist/stories/story-1/draft"]}>
      <LanguageProvider initialLanguage="en">
        <DraftTabB story={story} onStoryUpdate={jest.fn()} />
      </LanguageProvider>
    </MemoryRouter>,
  );
}

beforeEach(() => {
  jest.clearAllMocks();
});

describe("DraftTabB — Approve sends the version actually on screen", () => {
  it("approves the latest version (v2/model variant) by default, with its generationId", async () => {
    const story = makeStory();
    mockTransitionStatus.mockResolvedValue(story);
    renderDraftTab(story);

    await userEvent.click(screen.getByRole("button", { name: /approve current version/i }));

    await waitFor(() =>
      expect(mockTransitionStatus).toHaveBeenCalledWith(
        "story-1",
        "approved",
        expect.objectContaining({
          draft: expect.objectContaining({
            title: "V2 title (GPT variant)",
            body: "V2 body sentence, generated by the GPT variant.",
            sourceGenerationId: "gen-2",
          }),
        }),
      ),
    );
  });

  it("approves v1 after the specialist switches the timeline back to it", async () => {
    const story = makeStory();
    mockTransitionStatus.mockResolvedValue(story);
    renderDraftTab(story);

    // Switch the Draft tab to v1 in the version timeline.
    await userEvent.click(screen.getByText("v1"));

    await userEvent.click(screen.getByRole("button", { name: /approve current version/i }));

    await waitFor(() =>
      expect(mockTransitionStatus).toHaveBeenCalledWith(
        "story-1",
        "approved",
        expect.objectContaining({
          draft: expect.objectContaining({
            title: "V1 title",
            body: "V1 body sentence for approve test.",
            sourceGenerationId: "gen-1",
          }),
        }),
      ),
    );
  });

  it("approves manual edits made on top of the selected version", async () => {
    const story = makeStory();
    mockTransitionStatus.mockResolvedValue(story);
    (draftStore.updateStory as jest.Mock).mockResolvedValue(story);
    renderDraftTab(story);

    await userEvent.click(screen.getByRole("button", { name: /^edit$/i }));

    const textarea = screen.getByDisplayValue(
      "V2 body sentence, generated by the GPT variant.",
    );
    await userEvent.type(textarea, " Extra specialist edit.");

    // The readiness checklist requires edits to be saved before Approve
    // enables — save first, exactly as a specialist would in the UI.
    await userEvent.click(screen.getByRole("button", { name: /save draft/i }));
    await waitFor(() =>
      expect(screen.getByRole("button", { name: /approve current version/i })).toBeEnabled(),
    );

    await userEvent.click(screen.getByRole("button", { name: /approve current version/i }));

    await waitFor(() =>
      expect(mockTransitionStatus).toHaveBeenCalledWith(
        "story-1",
        "approved",
        expect.objectContaining({
          draft: expect.objectContaining({
            body: "V2 body sentence, generated by the GPT variant. Extra specialist edit.",
            sourceGenerationId: "gen-2",
          }),
        }),
      ),
    );
  });
});
