export interface StoryBrief {
  /** Firestore document ID */
  id?: string;

  /** Core routing fields (used by RAG) */
  topicKey: string;            // e.g. "fear_of_dark"
  targetAgeGroup: string;      // e.g. "4-6"

  /** Controlled vocabulary (used for pattern scoring) */
  topicTags: string[];         // e.g. ["night_fear", "bedtime_anxiety"]

  /** Human-defined therapeutic goals (NOT story text) */
  therapeuticIntent: string[]; // e.g. ["normalize night fear", "create bedtime safety"]

  /** Safety & boundary constraints */
  constraints: {
    avoidMetaphors?: string[]; // e.g. ["monsters", "hidden creatures"]
    avoidLanguage?: string[];  // e.g. ["be brave", "nothing to fear"]
  };

  /** Lifecycle status */
  status:
    | "draft"        // written by specialist
    | "generated"    // draft story generated by system
    | "reviewed"     // specialist reviewed
    | "approved";    // visible to users

  /** Audit & ownership */
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}
