// Central registry of the AI models Agent 1 can author a story with.
//
// A "version" of a story can be generated by any of these. The pipeline is
// model-agnostic — only the model id passed to the LLM client changes. Adding a
// new model is a single entry here plus (for non-Anthropic providers) a branch
// in llm-client.ts.

export type ModelChoice = "sonnet" | "gpt" | "opus";

/** The model used for the default single-version flow. */
export const DEFAULT_MODEL_CHOICE: ModelChoice = "sonnet";

/** Maps a ModelChoice to the concrete model id sent to the provider SDK. */
export const MODEL_IDS: Record<ModelChoice, string> = {
  sonnet: "claude-sonnet-4-6",
  gpt: "gpt-5.4",
  opus: "claude-opus-4-7",
};

/** Human-readable label shown on each generated version in the UI. */
export const MODEL_LABELS: Record<ModelChoice, string> = {
  sonnet: "Sonnet 4.6",
  gpt: "GPT-5",
  opus: "Opus 4.7",
};

export function isModelChoice(value: unknown): value is ModelChoice {
  return value === "sonnet" || value === "gpt" || value === "opus";
}

/** Resolves arbitrary input to a ModelChoice, falling back to the default. */
export function resolveModelChoice(value: unknown): ModelChoice {
  return isModelChoice(value) ? value : DEFAULT_MODEL_CHOICE;
}

/**
 * GPT-5 / o-series count reasoning tokens against max_completion_tokens. Values
 * that work for Claude (e.g. 4096) can be exhausted before any visible content.
 */
export function isOpenAIReasoningModel(model: string): boolean {
  return model.startsWith("o") || /^gpt-5/i.test(model);
}

/** Minimum completion budget for OpenAI reasoning models (Step 1–3). */
export const OPENAI_REASONING_MIN_COMPLETION_TOKENS = 16_384;

/** Boosted retry budget when the first OpenAI call returns no message content. */
export const OPENAI_REASONING_RETRY_COMPLETION_TOKENS = 32_768;

export function openAICompletionTokenBudget(model: string, requestedMax: number): number {
  if (!isOpenAIReasoningModel(model)) {
    return requestedMax;
  }
  return Math.max(requestedMax, OPENAI_REASONING_MIN_COMPLETION_TOKENS);
}
